name: pre_merge
on:
  pull_request:
  workflow_dispatch:

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: sync code
        run: |
          git clone https://github.com/qualcomm-linux/kernel.git
          git clone https://github.com/qualcomm-linux/automerge.git
          TOPIC_BRANCH=${{ github.ref }}
          do_conf() {
          	# Define the filename
          	FILENAME="merge.conf"
            # Create the file with the specified content
            cat <<EOF > "$FILENAME"
            baseline git@github.com:qualcomm-linux/kernel.git qcom-next 
            $TOPIC_BRANCH git@github.com:qualcomm-linux/kernel-topics.git $TOPIC_BRANCH
            EOF
          	echo "File '$FILENAME' created successfully."
          }
          do_conf
          cd kernel
          ../automerge/ci-merge -f ../merge.conf -t head -n
          
