name: pre_merge
on:
  pull_request:
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Create merge configuration
        run: |
          TOPIC_BRANCH=${{ github.base_ref }}
          cat <<EOF > merge.conf
          baseline git@github.com:qualcomm-linux/kernel.git qcom-next
          $TOPIC_BRANCH git@github.com:qualcomm-linux/kernel-topics.git $TOPIC_BRANCH
          EOF
          echo "File 'merge.conf' created successfully."

      - name: Run auto merge
        run: |
          cd kernel
          ../automerge/ci-merge -f ../merge.conf -t head -n

      - name: Fetch the PR 
        run: |
          cd kernel
          git fetch ${{ github.base_ref }} pull/${{ github.event.pull_request.number }}/head:pr-${{ github.event.pull_request.number }}
          git checkout pr-${{ github.event.pull_request.number }}

