name: pre_merge
on:
  pull_request:
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Clone repositories
        run: |
          git clone https://github.com/qualcomm-linux/kernel.git
          git clone https://github.com/qualcomm-linux/automerge.git

      - name: Create merge configuration
        run: |
          TOPIC_BRANCH=${{ github.base_ref }}
          cat <<EOF > merge.conf
          baseline git@github.com:qualcomm-linux/kernel.git qcom-next
          topic git@github.com:quic-viskuma/kernel-topics.git $TOPIC_BRANCH
          pr ${{ github.event.pull_request.ssh_url }} pull/${{ github.event.pull_request.number }}/head
          EOF
          echo "File 'merge.conf' created successfully."

      - name: Run auto merge
        run: |
          cd kernel
          ../automerge/ci-merge -f ../merge.conf -t head -n
