name: pre_merge
on:
  pull_request:
  workflow_dispatch:

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Clone repositories
        run: |
          git clone https://github.com/qualcomm-linux/kernel.git
          git clone https://github.com/qualcomm-linux/automerge.git

      - name: Create merge configuration
        run: |
          TOPIC_BRANCH=${{ github.ref }}
          cat <<EOF > merge.conf
          baseline git@github.com:qualcomm-linux/kernel.git qcom-next
          $TOPIC_BRANCH git@github.com:qualcomm-linux/kernel-topics.git $TOPIC_BRANCH
          EOF
          echo "File 'merge.conf' created successfully."

      - name: Run auto merge
        run: |
          cd kernel
          ../automerge/ci-merge -f ../merge.conf -t head -n
          
